name: Create Tag and Release note

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest release
        id: get-latest-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl -s -w "%{http_code}" -o curl_output.txt \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest)
          http_status=${response: -3}
          if [ "$http_status" -ne 200 ]; then
            echo "Failed to fetch latest release. HTTP status: $http_status"
            cat curl_output.txt
            exit 1
          fi
          tag_name=$(cat curl_output.txt | jq -r '.tag_name // empty')
          echo "latest_tag=$tag_name" >> $GITHUB_ENV

      - name: Calculate next tag
        id: calculate-next-tag
        run: |
          latest_tag="${{ env.latest_tag }}"

          if [[ "$latest_tag" =~ ^v([0-9]{4})\.([0-9]{2})\.([0-9]+)$ ]]; then
            current_year=$(date +"%Y")
            current_month=$(date +"%m")
            tag_year=${BASH_REMATCH[1]}
            tag_month=${BASH_REMATCH[2]}
            tag_number=${BASH_REMATCH[3]}

            # 年と月が一致する場合は番号をインクリメント
            if [[ "$tag_year" -eq "$current_year" && "$tag_month" -eq "$current_month" ]]; then
              next_number=$((tag_number + 1))
            else
              # 年または月が異なる場合は番号をリセット
              next_number=0
            fi
            next_tag="v${current_year}.${current_month}.$next_number"
          else
            echo "Error: latest_tag format is invalid!" >&2
            exit 1
          fi

          echo "next_tag=$next_tag" >> $GITHUB_ENV

      - name: Generate release notes
        id: generate-release-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl -s -w "%{http_code}" -o curl_output.txt -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "tag_name": "'${{ env.next_tag }}'",
              "previous_tag_name": "'${{ env.latest_tag }}'"
            }' \
            https://api.github.com/repos/${{ github.repository }}/releases/generate-notes)
          http_status=${response: -3}
          if [ "$http_status" -ne 200 ]; then
            echo "Failed to generate release notes. HTTP status: $http_status"
            cat curl_output.txt
            exit 1
          fi
          release_notes=$(cat curl_output.txt | jq -r '.body')

          release_notes_escaped=$(echo "$release_notes" | jq -sR '.')
          echo "RELEASE_NOTES=$release_notes_escaped" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NOTES: ${{ env.RELEASE_NOTES }}
        run: |
          response=$(curl -s -w "%{http_code}" -o curl_output.txt -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "tag_name": "'${{ env.next_tag }}'",
              "target_commitish": "main",
              "name": "'${{ env.next_tag }}'",
              "body": '"${RELEASE_NOTES}"',
              "draft": false,
              "prerelease": false
            }' \
            https://api.github.com/repos/${{ github.repository }}/releases)
          http_status=${response: -3}
          if [ "$http_status" -ne 201 ]; then
            echo "Failed to create release. HTTP status: $http_status"
            cat curl_output.txt
            exit 1
          fi

          tag_name="${{ env.next_tag }}"
          commit_sha=$(curl -s -H "Accept: application/vnd.github+json" \
                               -H "Authorization: Bearer $GITHUB_TOKEN" \
                               https://api.github.com/repos/${{ github.repository }}/git/ref/tags/$tag_name \
                         | jq -r '.object.sha')
          echo "latest_commit_sha=$commit_sha" >> $GITHUB_ENV

      - name: Create latest tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LATEST_TAG: latest
          LATEST_COMMIT_SHA: ${{ env.latest_commit_sha }}
        run: |
          # Create a tag object for 'latest'
          tag_object_response=$(curl -s -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "tag": "'${LATEST_TAG}'",
              "message": "This tag points to the latest release",
              "object": "'${LATEST_COMMIT_SHA}'",
              "type": "commit"
            }' \
            https://api.github.com/repos/${{ github.repository }}/git/tags)

          tag_object_sha=$(echo "$tag_object_response" | jq -r '.sha')

          curl -s -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "ref": "refs/tags/'${LATEST_TAG}'",
              "sha": "'${tag_object_sha}'"
            }' \
            https://api.github.com/repos/${{ github.repository }}/git/refs
