name: Create Tag and Release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest release
        id: get-latest-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl -s -w "%{http_code}" -o curl_output.txt \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest)
          http_status=${response: -3}
          if [ "$http_status" -ne 200 ]; then
            echo "Failed to fetch latest release. HTTP status: $http_status"
            cat curl_output.txt
            exit 1
          fi
          tag_name=$(cat curl_output.txt | jq -r '.tag_name // empty')
          echo "latest_tag=$tag_name" >> $GITHUB_ENV

      - name: Calculate next tag
        id: calculate-next-tag
        run: |
          latest_tag="${{ env.latest_tag }}"
          if [[ -z "$latest_tag" ]]; then
            echo "Error: No latest tag found and no default value provided." >&2
            exit 1
          fi

          if [[ "$latest_tag" =~ ^v([0-9]{4})\.([0-9]{2})\.([0-9]+)$ ]]; then
            current_year=${BASH_REMATCH[1]}
            current_month=${BASH_REMATCH[2]}
            tag_number=${BASH_REMATCH[3]}
            next_number=$((tag_number + 1))
            next_tag="v${current_year}.${current_month}.$next_number"
          else
            echo "Error: latest_tag format is invalid!" >&2
            exit 1
          fi

          echo "next_tag=$next_tag" >> $GITHUB_ENV

      - name: Generate release notes
        id: generate-release-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl -s -w "%{http_code}" -o curl_output.txt -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "tag_name": "'${{ env.next_tag }}'",
              "previous_tag_name": "'${{ env.latest_tag }}'"
            }' \
            https://api.github.com/repos/${{ github.repository }}/releases/generate-notes)
          http_status=${response: -3}
          if [ "$http_status" -ne 200 ]; then
            echo "Failed to generate release notes. HTTP status: $http_status"
            cat curl_output.txt
            exit 1
          fi
          release_notes=$(cat curl_output.txt | jq -r '.body')

          release_notes_escaped=$(echo "$release_notes" | jq -sR '.')
          echo "RELEASE_NOTES=$release_notes_escaped" >> $GITHUB_ENV

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NOTES: ${{ env.RELEASE_NOTES }}
        run: |
          response=$(curl -s -w "%{http_code}" -o curl_output.txt -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "tag_name": "'${{ env.next_tag }}'",
              "target_commitish": "main",
              "name": "'${{ env.next_tag }}'",
              "body": '"${RELEASE_NOTES}"',
              "draft": false,
              "prerelease": false
            }' \
            https://api.github.com/repos/${{ github.repository }}/releases)
          http_status=${response: -3}
          if [ "$http_status" -ne 201 ]; then
            echo "Failed to create release. HTTP status: $http_status"
            cat curl_output.txt
            exit 1
          fi
