name: hook create tag

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  deploy:
    name: echo
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: "echo Tag name: ${{ github.ref_name }}"
